variable "prefix" {}
variable "chap" {}
variable "cluster_type" {}
variable "resource_group_name" {}
variable "location" {}
variable "traffic_manager_profile_name" {}
variable "traffic_manager_endpoint_priority" {}
variable "cosmosdb_account_name" {}
variable "cosmosdb_account_primary_master_key" {}
