variable "prefix" {}
variable "chap" {}
variable "cluster_type" {}
variable "resource_group_name" {}
variable "location" {}
variable "aad_tenant_id" {}
variable "aad_ext_tenant_id" {}
variable "aad_client_app_id" {}
variable "aad_server_app_id" {}
variable "aad_server_app_secret" {}
